services:
  discovery:
    image: gateway-module-it-support
    container_name: gateway-module
    ports:
      - "8761:8761"
    networks:
      - it-support-network

networks:
  it-support-network:
    driver: bridge