spring:
  application:
    name: gateway

  cloud:
    gateway:
      locator:
        enabled: true
        lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    serviceUrl:
      defaultZone: http://localhost:8761/eureka/