spring:
  config:
    import: optional:classpath:.env[.properties]

  datasource:
    url: ${ENV_DATABASE_URL}
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}

  jpa:
    show-sql: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect