spring:
  datasource:
    url: ${ENV_DATABASE_URL}
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: none